apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-application
  namespace: argocd

spec:
  project: default
  sourse: 
    repoURL: https://github.com/seoyoomi/monolithic_k8s_aws.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernates.default.svc
    namespace: lgcns

  syncPolicy:
    automated:
      prune: true
      # 가장 핵심 : 클러스터 변경되면, git repo 기준으로 sync
      selfHeal: true