name: deploy order

on:
  push:
    branches:
      - main

jobs:
  # job name
  build-and-deploy:
    #runner
    runs-on: ubuntu-latest

    steps:
      - name: checkout github
        uses: actions/checkout@v2
      
      - name: install kubectl
        uses: azure/setup-kubectl@v3