name: deploy order

on:
  push:
    branches:
      - main

jobs:
  # job name
  build-and-deploy:
    #runner
    runs-on: ubuntu-latest

    steps:
      - name: checkout github
        uses: actions/checkoout@v2